config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help', as: 'help'
  get '/contact', to: 'static_pages#contact', as: 'contact'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  resources :users, only: %i[destroy index show] do
    member do
      get :following, :followers
    end
  end
  resources :posts
  resources :comments, except: %i[new show index]
  resources :relationships, only: %i[create destroy]
  resources :bookmarks, only: %i[create destroy]
end

app/views/shared/_alert_message.html.erb
<div class="alert_message wrapper">
  <p><%= alert %></p>
</div>

app/views/shared/_comment_form.html.erb
<div class="comment_form_outer">
  <div class="post_form_inner">
    <%= form_with(model: comment, class: "basic_form") do |f| %>
      <%= f.hidden_field :post_id %>
      <%= render('shared/error_messages', resource: comment) %>

      <%= f.label(:content, "コメント") %>
      <%= f.text_area(:content, class: "comment_textarea") %>

      <%= f.submit("投稿", class: "button") %>
    <% end %>
  </div>
</div>

app/views/shared/_comment_menu.html.erb
<div class="post_menu">
  <ul class="flex">
    <% if correct_user?(comment.user) || current_user_is_admin? %>
      <li><%= link_to("削除", "/comments/#{comment.id}",
        method: :delete,
        data: { confirm: '本当に削除しますか？' },
        class: "button") %>
      </li>
      <li><%= link_to("編集", edit_comment_path(comment), class: "button_border") %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_comment_show.html.erb
<div class="comment">
  <div class="comments_info">
    <div class="comments_user_icon">
      <%= link_to(user_path(comment.user)) do %>
        <%= render('shared/user_icon', user: comment.user) %>
      <% end %>
    </div>

    <div class="comment_meta">
      <div class="comment_inner">
        <div class="posts_meta">
          <p class="posted_user_name"><%= link_to(comment.user.name, user_path(comment.user)) %></p>
          <p class="updated_time"><%= comment.updated_at.to_s(:datetime_jp) %>更新</p>
        </div>
        <%= render('shared/comment_menu', comment: comment) %>
      </div>
    </div>
  </div>
  <p class="comment_content"><%= comment.content %></p>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li>・<%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="page_footer flex wrapper">
    <%= link_to(image_tag("logo.png", alt: "routine", class: "footer_logo"), root_path) %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="wrapper page_header">
    <h1><%= link_to(image_tag("logo.png", alt: "routine", class: "header_logo"), root_path) %></h1>
    
    <div class="search_box">
      <%= form_with(url: '/posts', method: :get) do |f| %>
        <%= f.text_field(:q, placeholder: '　記事を検索', class: 'search_box_form') %>
        <% f.submit('検索', class: 'button') %>
      <% end %>
    </div>

    <nav>
      <ul class="header_nav flex">
        <li><%= link_to("投稿一覧", posts_path) %></li>
        <li><%= link_to("投稿", new_post_path) %></li>
        <li><%= link_to("ユーザー一覧", users_path) %></li>

        <% if user_signed_in? %>
          <li><%= link_to("#{current_user.name}", current_user, class: "button") %></li>
          <li><%= link_to("ログアウト", destroy_user_session_path, method: :delete, class: "button") %></li>
        <% else %>
          <li><%= link_to("新規登録", new_user_registration_path, class: "button") %></li>
          <li><%= link_to("ログイン", new_user_session_path, class: "button_border") %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_post_info.html.erb
<div class="post_info">
  <div class="post_user_icon">
    <%= link_to(users_path(post.user)) do %>
      <%= render('shared/user_icon', user: post.user) %>
    <% end %>
  </div>

  <div class="posts_meta">
    <h2 class="post_title"><%= link_to(post.title, post_path(post)) %></h2>

    <p class="posted_user_name"><%= link_to(post.user.name,user_path(post.user)) %></p>
    <p class="updated_time"><%= post.updated_at.to_s(:datetime_jp) %>更新</p>
  </div>
</div>

app/views/shared/_post_menu.html.erb
<div class="post_menu">
  <ul class="flex">
    <% if correct_user?(post.user) || current_user_is_admin? %>
      <li><%= link_to("削除", post,
        method: :delete,
        data: { confirm: '本当に削除しますか？' },
        class: "button") %>
      </li>
      <li><%= link_to("編集", edit_post_path(post), class: "button_border") %></li>
    <% else %>
      <%= render('posts/bookmark_button', post: post) %>
    <% end %>
  </ul>
</div>

app/views/shared/_posts_index.html.erb
<div class="posts">
  <% if posts.blank? %>
    <div class="posts_nil">
      <h2>まだ投稿がありません</h2>
    </div>
  <% else %>
    <% posts.each do |post| %>
      <div class="post">
        <%= render('shared/post_info', post: post) %>
      </div>
    <% end %>
  <% end %>

  <%= will_paginate(posts, previous_label: '<', next_label: '>', inner_window: 1) %>
</div>

app/views/shared/_user_icon.html.erb
<% if user.icon.blank? %>
  <%= image_tag('default_icon', class: 'user_icon') %>
<% else %>
  <%= image_tag(user.icon.url, class: 'user_icon', alt: 'user icon') %>
<% end %>

app/views/shared/_user_info.html.erb
<div class="item_content">
  <div class="post_user_icon">
    <%= link_to(users_path(user)) do %>
      <%= render('shared/user_icon', user: user) %>
    <% end %>
  </div>

  <h2 class="user_name"><%= link_to(user.name, user_path(user)) %></h2>
</div>

app/views/shared/_users_index.html.erb
<div class="items_index">
  <% if users.blank? %>
    <div class="items_nil">
      <h2>まだユーザーがいません</h2>
    </div>
  <% else %>
    <% users.each do |user| %>
      <% next if user.admin %>
      <div class="index_item">
        <%= render('shared/user_info', user: user) %>
      </div>
    <% end %>
    <%= will_paginate(@users, previous_label: '<', next_label: '>', inner_window: 1) %>
  <% end %>
</div>

app/views/shared/_users_not_exist.html.erb
<div class="items_index">
  <% if users.blank? %>
    <div class="items-nil">
      <h2>まだユーザーがいません</h2>
    </div>
  <% else %>
    <% users.each do |user| %>
      <div class="index_item">
        <%= render 'shared/user_info', user: user %>
      </div>
    <% end %>
  <% end %>
</div>